create table if not exists public.signups (
  id bigint generated by default as identity primary key,
  name text not null default '',
  email text not null,
  company text not null default '',
  interest text not null default '',
  submitted_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.signups alter column name set default '';
alter table if exists public.signups alter column company set default '';
alter table if exists public.signups alter column interest set default '';

create index if not exists signups_submitted_at_idx on public.signups (submitted_at desc);
