create table if not exists public.signups (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text not null,
  interest text not null default '',
  submitted_at timestamptz not null default timezone('utc', now())
);

create index if not exists signups_submitted_at_idx on public.signups (submitted_at desc);
